---
title: "DataFrame"
author: "Alice Roberts"
date: "2/1/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r Team Data (5)}
set.seed(123)
#Creating the dataset for our Team for display 

FirstName <- c("Alice", "Kristen", "Zhi Yuh", "Charlene", "Nicholas","New")
LastName <- c("Roberts", "Bystrom", "Ou Yang", "Nicer", "Chin","User")
EmployeeNumber <-c(301288793, 301252960, 301322064, 24600165, 54101167,1111111)
Job<- c("Senior Optimization Analyst","Applied Data Scientist", "Financial Analyst", "Software Developer II- IT Integration","Senior Software Developer- eCommerce Web","Business Analyst")
YearsofExperience<- c(15,6,12,3,10,1)
OfficeLocation<- c("Vancouver","Vancouver","Vancouver","Vancouver","Vancouver","Vancouver")
Age<- c(35,28,35,24,30,21)
Department <- c("Data + Analytics","Data + Analytics", "Finance + Accounting", "Software Development","Software Development","Data + Analytics")

##Performance out of 10 
PerformanceScore <-c(9,10,7,8,10,5)
Salary <- c(150000,120000,100000,90000,110000,80000)

# Socre between: 0 1 or 2  where 0 means no, 1 means yes, 2 means wants to learn

agile.methodology <- c(1,1,2,1,1,0)
public.speaking <- c(1,2,0,0,1,1)
python <-c(2,1,0,1,1,0)
R <-c(1,1,1,2,0,2)
Excel <-c(1,1,1,2,0,2)
Cplusplus <-c(2,0,0,1,1,0)
Java <- c(0,0,2,1,1,1)

TeamData <- data.frame(FirstName,LastName,EmployeeNumber, Department,Job,OfficeLocation, YearsofExperience,Age,PerformanceScore,Salary,agile.methodology,public.speaking,python,R,Excel,Cplusplus,Java)

head(TeamData)
# Write CSV in R
write.csv(TeamData, file = "TeamData.csv")


```


```{r Random Data (1000)}
n=1000

#Retrieving random names from a random CSV file lol 
Records <- read.csv("~/Desktop/1000 Records.csv");

FirstName <- Records$First.Name
LastName <- Records$Last.Name
EmployeeNumber <- sample(10000000, size = n, replace = FALSE)

Departments <- c("Data + Analytics", "Finance + Accounting","Software Development")

Department <- sample(Departments, size=n,replace=TRUE)

JobData <- c( "Senior Optimization Analyst", "Applied Data Scientist", "Digital Analytics Developer, Practice Lead")

JobFinance <- c("Senior Business Analyst - Controllership", "Senior Accountant, Lease & Real Estate", "Intermediate Accountant, Advertising", "Financial Analyst","Intermediate Accountant, Severance & Benefits" )

JobSoftware <- c("Software Developer II - IT Integration","Senior Software Developer","Software Developer II - eCommerce","Software Developer II - IT", "Senior Software Developer - eCommerce Web")

#check if the deparment is blah, then return the job
JobFunction <- function(Department){

  if(Department == "Data + Analytics")
  {
    Job1<- sample(JobData, size=1)
  }
   
  if(Department == "Finance + Accounting")
  {
    Job1<- sample(JobFinance, size=1)
  }
  if(Department == "Software Development")
  {
    Job1<- sample(JobSoftware, size=1)
  }
   
return(Job1)
}
Job =  sapply(Department,JobFunction)

#For simplicity we will just use Vancouver
OfficeLocations<- "Vancouver"
OfficeLocation <- sample(OfficeLocations, size=n, replace=TRUE)


Age <- sample(20:65, size=n, replace=TRUE)


ExperienceFunction<- function(Age){

 PE = Age-20
   YearsofExperience1 <- sample(0:PE, size=1)
     
     return(YearsofExperience1)

}
YearsofExperience =  sapply(Age,ExperienceFunction)



PerformanceScore <- sample(1:10, size=n, replace =TRUE)
Salary <- sample(seq(60000,200000,by = 10000), size=n, replace=TRUE)


agile.methodology <- sample(0:2, size=n,replace=TRUE)
public.speaking <- sample(0:2, size=n,replace=TRUE)
python <- sample(0:2, size=n,replace=TRUE)
R <- sample(0:2, size=n,replace=TRUE)
Excel <- sample(0:2, size=n,replace=TRUE)
Cplusplus <- sample(0:2, size=n,replace=TRUE)
Java <- sample(0:2, size=n,replace=TRUE)


RandomData <- data.frame(FirstName,LastName,EmployeeNumber, Department,Job,OfficeLocation, YearsofExperience,Age,PerformanceScore,Salary,agile.methodology,public.speaking,python,R,Excel,Cplusplus,Java)


head(RandomData)
# Write CSV in R
write.csv(RandomData, file = "RandomData.csv")

```



```{r Creating Function}
#Getting rid of not important stuff 
RandomData[,c("PerformanceScore","YearsofExperience")] <- NULL
head(RandomData)

## hardcoding number of skills we have 
maxnumskills <- 7

## Creating a function that matches people based on if they both require each other. 
## Person is a single row with all variables for one single person
#Returns a list where the first item is the number of skilled desired and the rest are the row of the matches associated 

MatchFunction <- function(Person,RandomData)
{
  OptMatches<- NA
## Seeing if this person has a skill that they want
    if (any(Person ==2))
    {
      ## finding the col number(s) of the skills wanted
      colnum<- which(Person == 2)

      ## number of skills wanted 
      numskillsdesired<-length(colnum)
      
      ##finding the row numbers of people that have the skill
      MATCH <-rep( list(list()), numskillsdesired ) 
      
          for (i in 1:(numskillsdesired))
          {
            MATCH[[i]]<-which((RandomData[,colnum[i]]==1))
        
          }
  
      
      RandomData$count <- rep(0, length(RandomData$EmployeeNumber)) 
      
          for (i in 1:(numskillsdesired))
          {
              RandomData$count = RandomData$count + ifelse(as.numeric(rownames(RandomData)) %in%  MATCH[[i]],1,0)
          }
  
  
      OptMatches<-RandomData[with(RandomData,order(-count)), ]
  
  
  
      }
  
  return(OptMatches) 

}

#returns the dataframe in the desired order 
```


```{r Implementing Function}
head(RandomData)
Person <- RandomData[2,]
Result1<-MatchFunction(Person,RandomData)
Result1
```


